### PR TITLE
Moved tokens from process memory to file with async access

### PR DESCRIPTION
**Pull request by DarkKlaw**

### CODE REVIEW

**Review by cccs-is — COMMENTED** [review]
This is a great idea! 
Can this be an option for the users to configure. I can see a need for both cases, the in-memory storage (more secure) and on disk storage for your use case.

**Comment by DarkKlaw** [comment]
> This is a great idea! Can this be an option for the users to configure. I can see a need for both cases, the in-memory storage (more secure) and on disk storage for your use case.

Good point. I will make these changes next week.

**Comment by DarkKlaw** [comment]
> > This is a great idea! Can this be an option for the users to configure. I can see a need for both cases, the in-memory storage (more secure) and on disk storage for your use case.
> 
> Good point. I will make these changes next week.

@cccs-is Just made the changes. Let me know if you have any other comments/concerns.

**Review by cccs-is — APPROVED** [review]
Thanks!

**Comment by DarkKlaw** [comment]
> Thanks!

Feel free to merge in main (since I cannot)

**Comment by cccs-is** [comment]
Ah, I forgot about that.

**Pull request merged**
